# Generated by Django 5.2 on 2025-08-06 12:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catpresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='marque_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=75)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='cat_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=75)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('marque_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.marque_prod')),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prixu', models.BigIntegerField(default=0, null=True)),
                ('qte', models.BigIntegerField(default=0, null=True)),
                ('seuil', models.BigIntegerField(default=0, null=True)),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cat_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.cat_prod')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.marque_prod')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('proprietaire', models.CharField(default='', max_length=200)),
                ('contact_pro', models.CharField(default='', max_length=200)),
                ('gerant', models.CharField(default='', max_length=200, null=True)),
                ('contact_gerant', models.CharField(default='', max_length=200, null=True)),
                ('gps', models.CharField(default='', max_length=200)),
                ('commentaire', models.CharField(default='', max_length=200)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region')),
            ],
        ),
        migrations.CreateModel(
            name='Basedom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region')),
            ],
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0)),
                ('remise', models.BigIntegerField(default=0)),
                ('net_payer', models.BigIntegerField(default=0)),
                ('statut', models.CharField(default='', max_length=10)),
                ('commentaire', models.CharField(default='', max_length=200)),
                ('datevente', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('etat', models.CharField(default='', max_length=20)),
                ('kmsdebut', models.IntegerField(default=0, null=True)),
                ('kmsfin', models.IntegerField(default=0, null=True)),
                ('nbreJtravail', models.IntegerField(default=0, null=True)),
                ('objectifvisite', models.IntegerField(default=0, null=True)),
                ('visiterealise', models.IntegerField(default=0, null=True)),
                ('visiteplanifie', models.IntegerField(default=0, null=True)),
                ('pdvreussit', models.IntegerField(default=0, null=True)),
                ('nbremoyskupdv', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('objectifvente', models.IntegerField(default=0, null=True)),
                ('venterealise', models.IntegerField(default=0, null=True)),
                ('nbrebso', models.IntegerField(default=0, null=True)),
                ('Catpresta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.catpresta')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.client')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ligne_vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.BigIntegerField(default=0)),
                ('prixu', models.BigIntegerField(default=0)),
                ('net_vente', models.BigIntegerField(default=0)),
                ('datevente', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.vente')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region')),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=20)),
                ('adressemail', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('profil', models.CharField(default='', max_length=50)),
                ('datenaiss', models.DateTimeField(blank=True, default='', max_length=50)),
                ('lieunaiss', models.CharField(default='', max_length=50)),
                ('lieuresidence', models.CharField(default='', max_length=50)),
                ('cni', models.CharField(default='', max_length=50)),
                ('login', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('Basedom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.basedom')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.ville')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.ville'),
        ),
        migrations.AddField(
            model_name='basedom',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.ville'),
        ),
    ]
