# Generated by Django 5.2 on 2025-05-22 16:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=20)),
                ('adressemail', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('profil', models.CharField(default='', max_length=50)),
                ('datenaiss', models.DateTimeField(blank=True, default='', max_length=50)),
                ('lieunaiss', models.CharField(default='', max_length=50)),
                ('lieuresidence', models.CharField(default='', max_length=50)),
                ('cni', models.CharField(default='', max_length=50)),
                ('login', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
            ],
        ),
        migrations.CreateModel(
            name='marque_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=75)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='type_pv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='zonecouv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='cat_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=75)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('marque_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.marque_prod')),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prixu', models.BigIntegerField(default=0, null=True)),
                ('qte', models.BigIntegerField(default=0, null=True)),
                ('seuil', models.BigIntegerField(default=0, null=True)),
                ('couleur', models.CharField(default='', max_length=50, null=True)),
                ('description', models.CharField(default='', max_length=200, null=True)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.cat_prod')),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.marque_prod')),
            ],
        ),
        migrations.CreateModel(
            name='pointv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('proprietaire', models.CharField(default='', max_length=200)),
                ('contact_pro', models.CharField(default='', max_length=200)),
                ('gerant', models.CharField(default='', max_length=200)),
                ('contact_gerant', models.CharField(default='', max_length=200)),
                ('ville', models.CharField(default='', max_length=200)),
                ('commune', models.CharField(default='', max_length=200)),
                ('quartier', models.CharField(default='', max_length=200)),
                ('gps', models.CharField(default='', max_length=200)),
                ('commentaire', models.CharField(default='', max_length=200)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('type_pv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.type_pv')),
            ],
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0)),
                ('remise', models.BigIntegerField(default=0)),
                ('net_payer', models.BigIntegerField(default=0)),
                ('statut', models.CharField(default='', max_length=10)),
                ('commentaire', models.CharField(default='', max_length=200)),
                ('datevente', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('commercial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.commercial')),
                ('pointv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.pointv')),
            ],
        ),
        migrations.CreateModel(
            name='ligne_vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.BigIntegerField(default=0)),
                ('prixu', models.BigIntegerField(default=0)),
                ('prix_total', models.BigIntegerField(default=0)),
                ('remise', models.BigIntegerField(default=0)),
                ('datevente', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('commercial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.commercial')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.produit')),
                ('vente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.vente')),
            ],
        ),
        migrations.AddField(
            model_name='commercial',
            name='zonecouv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.zonecouv'),
        ),
    ]
