# Generated by Django 5.2 on 2025-05-13 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='commercial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=20)),
                ('adressemail', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='marque_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='type_pv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('prixu', models.BigIntegerField(default=0)),
                ('qte', models.BigIntegerField(default=0)),
                ('seuil', models.BigIntegerField(default=0)),
                ('couleur', models.CharField(default='', max_length=50)),
                ('description', models.CharField(default='', max_length=200)),
                ('marque_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.marque_prod')),
            ],
        ),
        migrations.CreateModel(
            name='pointv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('proprietaire', models.CharField(default='', max_length=200)),
                ('contact_pro', models.CharField(default='', max_length=200)),
                ('gerant', models.CharField(default='', max_length=200)),
                ('contact_gerant', models.CharField(default='', max_length=200)),
                ('ville', models.CharField(default='', max_length=200)),
                ('commune', models.CharField(default='', max_length=200)),
                ('quartier', models.CharField(default='', max_length=200)),
                ('gps', models.CharField(default='', max_length=200)),
                ('commentaire', models.CharField(default='', max_length=200)),
                ('type_pv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.type_pv')),
            ],
        ),
        migrations.CreateModel(
            name='user_plus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=20)),
                ('droit', models.CharField(default='', max_length=10)),
                ('photoid', models.ImageField(default='', upload_to='')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.BigIntegerField(default=0)),
                ('remise', models.BigIntegerField(default=0)),
                ('net_payer', models.BigIntegerField(default=0)),
                ('statut', models.CharField(default='', max_length=10)),
                ('commentaire', models.CharField(default='', max_length=200)),
                ('commercial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.commercial')),
                ('pointv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.pointv')),
            ],
        ),
        migrations.CreateModel(
            name='ligne_vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.BigIntegerField(default=0)),
                ('prixu', models.BigIntegerField(default=0)),
                ('prix_total', models.BigIntegerField(default=0)),
                ('commercial_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.commercial')),
                ('produit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.produit')),
                ('vente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.vente')),
            ],
        ),
    ]
