# Generated by Django 5.2 on 2025-05-14 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercial',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ligne_vente',
            name='datevente',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='marque_prod',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='pointv',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='produit',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='type_pv',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user_plus',
            name='datecreation',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='vente',
            name='datevente',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='produit',
            name='couleur',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='description',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='prixu',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='qte',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='produit',
            name='seuil',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
