# Generated by Django 5.2 on 2025-08-12 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gps',
        ),
    ]
