# Generated by Django 5.2 on 2025-08-14 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_remove_client_gps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='remise',
        ),
    ]
