# Generated by Django 5.2 on 2025-05-14 14:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_commercial_datecreation_ligne_vente_datevente_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ligne_vente',
            old_name='produit_id',
            new_name='produit',
        ),
        migrations.RenameField(
            model_name='pointv',
            old_name='type_pv_id',
            new_name='type_pv',
        ),
        migrations.RenameField(
            model_name='user_plus',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='commercial_id',
            new_name='commercial',
        ),
        migrations.RenameField(
            model_name='vente',
            old_name='pointv_id',
            new_name='pointv',
        ),
        migrations.CreateModel(
            name='cat_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=75)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('marque_prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.marque_prod')),
            ],
        ),
    ]
