# Generated by Django 5.2 on 2025-05-27 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_ligne_vente_net_payer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='commercial',
        ),
    ]
