# Generated by Django 5.2 on 2025-08-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_remove_vente_remise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='montant',
        ),
    ]
