# Generated by Django 5.2 on 2025-05-14 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0003_rename_produit_id_ligne_vente_produit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produit',
            old_name='marque_id',
            new_name='marque',
        ),
        migrations.AddField(
            model_name='produit',
            name='cat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.cat_prod'),
            preserve_default=False,
        ),
    ]
