# Generated by Django 5.2 on 2025-08-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0004_remove_vente_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='statut',
        ),
    ]
