# Generated by Django 5.2 on 2025-05-27 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_alter_ligne_vente_commercial_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_vente',
            name='commercial_id',
        ),
    ]
