# Generated by Django 5.2 on 2025-12-10 09:00

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_vente_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Catcli',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Catpresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=200)),
                ('proprietaire', models.CharField(default='', max_length=200)),
                ('contact_pro', models.CharField(default='', max_length=200)),
                ('gerant', models.CharField(default='', max_length=200, null=True)),
                ('contact_gerant', models.CharField(default='', max_length=200, null=True)),
                ('commentaire', models.CharField(default='', max_length=200)),
                ('gps', models.CharField(default='', max_length=200)),
                ('gpsx', models.CharField(default='', max_length=200)),
                ('gpsy', models.CharField(default='', max_length=200)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='type_pv',
            new_name='Canalcli',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='commercial',
        ),
        migrations.RemoveField(
            model_name='ligne_vente',
            name='commercial_id',
        ),
        migrations.RemoveField(
            model_name='pointv',
            name='type_pv',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='pointv',
        ),
        migrations.RemoveField(
            model_name='user_plus',
            name='user',
        ),
        migrations.RenameField(
            model_name='ligne_vente',
            old_name='prix_total',
            new_name='net_vente',
        ),
        migrations.RenameField(
            model_name='ligne_vente',
            old_name='vente_id',
            new_name='vente',
        ),
        migrations.RenameField(
            model_name='produit',
            old_name='cat',
            new_name='cat_prod',
        ),
        migrations.RemoveField(
            model_name='produit',
            name='couleur',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='montant',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='remise',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='statut',
        ),
        migrations.AddField(
            model_name='vente',
            name='etat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='gps',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vente',
            name='gpsx',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vente',
            name='gpsy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vente',
            name='nbrebso',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='objectifvente',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='venterealise',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='vente',
            name='Catpresta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.catpresta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='Client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.client'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Journe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(default='', max_length=200, null=True)),
                ('datejoune', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('etat', models.CharField(default='', max_length=20)),
                ('objectifjourne', models.IntegerField(default=0, null=True)),
                ('ventejourne', models.IntegerField(default=0, null=True)),
                ('visiterealise', models.IntegerField(default=0, null=True)),
                ('visiteplanifie', models.IntegerField(default=0, null=True)),
                ('pdvreussit', models.IntegerField(default=0, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='Journe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdv.journe'),
        ),
        migrations.AddField(
            model_name='client',
            name='Region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region'),
        ),
        migrations.CreateModel(
            name='Basedom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region')),
            ],
        ),
        migrations.CreateModel(
            name='Ville',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region')),
            ],
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='', max_length=100)),
                ('contact', models.CharField(default='', max_length=20)),
                ('adressemail', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('profil', models.CharField(default='', max_length=50)),
                ('datenaiss', models.DateTimeField(blank=True, default='', max_length=50)),
                ('lieunaiss', models.CharField(default='', max_length=50)),
                ('lieuresidence', models.CharField(default='', max_length=50)),
                ('cni', models.CharField(default='', max_length=50)),
                ('login', models.CharField(default='', max_length=50)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/')),
                ('Basedom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.basedom')),
                ('Region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Ville', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.ville')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.ville'),
        ),
        migrations.AddField(
            model_name='basedom',
            name='Ville',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.ville'),
        ),
        migrations.DeleteModel(
            name='commercial',
        ),
        migrations.DeleteModel(
            name='pointv',
        ),
        migrations.DeleteModel(
            name='user_plus',
        ),
    ]
