# Generated by Django 5.2 on 2025-08-29 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0005_remove_vente_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='kmsdebut',
        ),
        migrations.RemoveField(
            model_name='vente',
            name='kmsfin',
        ),
    ]
