# Generated by Django 5.2 on 2025-09-24 10:14

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0006_remove_vente_kmsdebut_remove_vente_kmsfin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gps',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='gpsx',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='client',
            name='gpsy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vente',
            name='gps',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vente',
            name='gpsx',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='vente',
            name='gpsy',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.CreateModel(
            name='Journe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commentaire', models.CharField(default='', max_length=200, null=True)),
                ('datejoune', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('etat', models.CharField(default='', max_length=20)),
                ('objectifjourne', models.IntegerField(default=0, null=True)),
                ('ventejourne', models.IntegerField(default=0, null=True)),
                ('visiterealise', models.IntegerField(default=0, null=True)),
                ('visiteplanifie', models.IntegerField(default=0, null=True)),
                ('gps', models.CharField(default='', max_length=200)),
                ('gpsx', models.CharField(default='', max_length=200)),
                ('gpsy', models.CharField(default='', max_length=200)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='vente',
            name='Journe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdv.journe'),
        ),
    ]
