# Generated by Django 5.2 on 2025-12-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0006_catcli_catpresta_client_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendeur',
            name='Basedom',
        ),
    ]
