# Generated by Django 5.2 on 2025-09-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_client_gps_client_gpsx_client_gpsy_vente_gps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Journe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pdv.journe'),
        ),
    ]
