# Generated by Django 5.2 on 2025-12-10 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_remove_vendeur_basedom'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_vente',
            name='Codevente',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='vente',
            name='Codevente',
            field=models.CharField(default='', max_length=20),
        ),
    ]
