# Generated by Django 5.2 on 2025-09-24 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0008_alter_vente_journe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vente',
            name='Journe',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='pdv.journe'),
        ),
    ]
