# Generated by Django 5.2 on 2025-12-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0008_ligne_vente_codevente_vente_codevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='Canalcli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.canalcli'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='Catcli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.catcli'),
            preserve_default=False,
        ),
    ]
