# Generated by Django 5.2 on 2025-09-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0009_alter_vente_journe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journe',
            name='gps',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journe',
            name='gpsx',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='journe',
            name='gpsy',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='gps',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='gpsx',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vente',
            name='gpsy',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
