# Generated by Django 5.2 on 2025-12-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0009_client_canalcli_client_catcli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_vente',
            name='vente',
        ),
    ]
