# Generated by Django 5.2 on 2025-12-11 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0010_remove_ligne_vente_vente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_vente',
            name='vente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.vente'),
            preserve_default=False,
        ),
    ]
