# Generated by Django 5.2 on 2025-09-24 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0011_alter_journe_gps_alter_journe_gpsx_alter_journe_gpsy_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journe',
            name='gps',
        ),
        migrations.RemoveField(
            model_name='journe',
            name='gpsx',
        ),
        migrations.RemoveField(
            model_name='journe',
            name='gpsy',
        ),
    ]
