# Generated by Django 5.2 on 2025-12-11 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0011_ligne_vente_vente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='nbrebso',
        ),
    ]
