# Generated by Django 5.2 on 2025-12-11 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0012_remove_vente_nbrebso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ligne_vente',
            name='Codevente',
        ),
    ]
