# Generated by Django 5.2 on 2025-09-24 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0012_remove_journe_gps_remove_journe_gpsx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vente',
            name='nbreJtravail',
        ),
    ]
