# Generated by Django 5.2 on 2025-05-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0002_commercial_user_alter_pointv_contact_gerant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ligne_vente',
            name='net_payer',
            field=models.BigIntegerField(default=0),
        ),
    ]
