# Generated by Django 5.2 on 2025-07-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0006_remove_ligne_vente_commercial_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vente',
            name='etat',
            field=models.CharField(default='', max_length=20),
        ),
    ]
