# Generated by Django 5.2 on 2025-07-31 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0007_vente_etat'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointv',
            name='zonecouv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.zonecouv'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vente',
            name='zonecouv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.zonecouv'),
            preserve_default=False,
        ),
    ]
