# Generated by Django 5.2 on 2025-08-06 09:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdv', '0008_pointv_zonecouv_vente_zonecouv'),
    ]

    operations = [
        migrations.CreateModel(
            name='catpresta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='', max_length=50)),
                ('datecreation', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='zonecouv',
            name='region',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='vente',
            name='catpresta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pdv.catpresta'),
            preserve_default=False,
        ),
    ]
